spring:
  application:
    name: portfolio
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/portfolio}
    username: ${SPRING_DATASOURCE_USERNAME:portfolio}
    password: ${SPRING_DATASOURCE_PASSWORD:changeme}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

server:
  port: 8080
